name: object_detection
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # ✅ Ultralytics official plugin (newer overlay + segmentation support)
  ultralytics_yolo: ^0.2.0
  flutter_tts: ^3.8.5

  # 🔔 Notifications
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.4

  # 📍 Location
  geolocator: ^9.0.2

  permission_handler: ^12.0.1
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/models/
